name: Build dummy monitor

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Taskfile
        uses: arduino/setup-task@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Build
        run: task build-dummy-monitor
